### ISSUE TITLE
window scroll is getting change when press the enter in textarea

### ISSUE THREAD

**Issue by ashanvabs** [CodingAspect/Textarea-Autogrow#3]
normally its working perfectly.
and when text area grow and scroll bar is appear beacause of that.
then text area's bottom will be near to bottom of the brower.
after that 
when typing page is moving to bit up and when press the enter button page is moving bit down. 
It's really anoying :(

**Comment by evyros** [comment]
I'm not familiar with this issue, so there's a chance it's a bug that's not related to this library.
Can you upload a reproduction? It would be greatly appreciated.
